# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Xilinxworkspace/Lab_11_2/Lab_11_2.cache/wt [current_project]
set_property parent.project_path E:/Xilinxworkspace/Lab_11_2/Lab_11_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Xilinxworkspace/Lab_11_2 [current_project]
update_ip_catalog
set_property ip_output_repo e:/Xilinxworkspace/Lab_11_2/Lab_11_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/new/RGB_light.v
  E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/new/Lab_11_2.v
}
read_ip -quiet e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/rgb2dvi_0_1/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi_clocks.xdc]

read_ip -quiet E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/OV5647_Init_0/OV5647_Init_0.xci

read_ip -quiet E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_MIPI_0/Driver_MIPI_0.xci
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_MIPI_0/src/csi_to_axis_0/hdl/csi_to_axis.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_MIPI_0/src/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_MIPI_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_IIC_0/Driver_IIC_0.xci

read_ip -quiet e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Driver_SK6805_0/Driver_SK6805_0.xci

read_ip -quiet e:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/sources_1/ip/Clk_Division_0/Clk_Division_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files E:/Xilinxworkspace/Lab_11_2/Lab_11_2.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Lab_11_2 -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Lab_11_2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Lab_11_2_utilization_synth.rpt -pb Lab_11_2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
